const year1Words = {
  metadata: {
    year: 1,
    totalSections: 5
  },
  sections: {
    'E1': [
      {
        name: "E1: Ich und die anderen (Teil 1)",
        words: [
          { german: 'r Buchstabe, -n', english: 'letter' },
          { german: 'buchstabieren', english: 'to spell' },
          { german: 's Land, Länder', english: 'country, state' },
          { german: 'r Bewohner, -', english: 'resident' },
          { german: 'e Bewohnerin, -nen', english: 'female resident' },
          { german: 'Ich heiße', english: 'My name is ...' },
          { german: 'Mein Name ist', english: 'My name is ...' },
          { german: 'Ich bin', english: 'I am ...' },
          { german: 'r Name, -n', english: 'name or surname' },
          { german: 'r Vorname, -n', english: 'first name' },
          { german: 'r Nachname, -n', english: 'surname' },
          { german: 'r Familienname, -n', english: 'surname2' },
          { german: 'r Wohnort, -e', english: 'place of residence' },
          { german: 'e Adresse, -n', english: 'address' },
          { german: 's Jahr, -e', english: 'year' },
          { german: 's Alter, -', english: 'age' },
          { german: 'Ich bin ... Jahre alt.', english: 'I am ... years old.' },
          { german: 'e Sprache, -n', english: 'language' },
          { german: 'e Fremdsprache, -n', english: 'foreign language' },
          { german: 'e Muttersprache, -n', english: 'native language' },
          { german: 'e Herkunft', english: 'origin' },
          { german: 'Guten Tag!', english: 'Good day!' },
          { german: 'Grüß Gott!', english: 'Good day! (Austria)' },
          { german: 'Grüezi!', english: 'Good day! (Switzerland)' },
          { german: 'Hallo!', english: 'Hello!' },
          { german: 'Grüß dich!', english: 'Hello! (informal, singular)' },
          { german: 'Grüß euch!', english: 'Hello! (informal, plural)' },
          { german: 'Guten Morgen!', english: 'Good morning!' },
          { german: 'Guten Abend!', english: 'Good evening!' },
          { german: 'Tschüss!', english: 'Bye!' },
          { german: 'Auf Wiedersehen!', english: 'Goodbye!' },
          { german: 'Bis bald!', english: 'See you soon!' },
          { german: 'Bis dann!', english: 'See you then!' },
          { german: 'Bis morgen!', english: 'See you tomorrow!' },
          { german: 'Bis später!', english: 'See you later!' },
          { german: 'Bis Mittwoch!', english: 'See you on Wednesday!' },
          { german: 'in', english: 'in' },
          { german: 'bei', english: 'at, with' },
          { german: 'aus', english: 'from' },
          { german: 'über', english: 'about' },
          { german: 'und', english: 'and' },
          { german: 'oder', english: 'or' },
          { german: 'aber', english: 'but' },
          { german: 'noch', english: 'still' },
          { german: 'schon', english: 'already' },
          { german: 'haben', english: 'to have' },
          { german: 'sein', english: 'to be' },
          { german: 'kommen', english: 'to come' },
          { german: 'wohnen', english: 'to live, reside' },
          { german: 'gehen', english: 'to go' },
          { german: 'heißen', english: 'to be called' },
          { german: 'sprechen', english: 'to speak' },
          { german: 'leben', english: 'to live' },
          { german: 'lernen', english: 'to learn' },
          { german: 'stehen', english: 'to stand' },
          { german: 'e Zahl, -en', english: 'number' },
          { german: 'zählen', english: 'to count' },
          { german: 'rechnen', english: 'to calculate' },
          { german: 'e Telefonnummer, -n', english: 'telephone number' },
          { german: 'e Handynummer, -n', english: 'mobile number' },
          { german: 's Handy, -s', english: 'mobile phone' },
          { german: 'e Postleitzahl, -en', english: 'postal code' },
          { german: 'Meine Handynummer ist', english: 'My telephone/mobile number is' },
          { german: 'r Beruf, -e', english: 'profession' },
          { german: 'das', english: 'that, the' },
          { german: 'Was ist das?', english: 'What is that?' },
          { german: 'Wer ist das?', english: 'Who is that?' },
          { german: 'wer', english: 'who' },
          { german: 'was', english: 'what' },
          { german: 'wann', english: 'when' },
          { german: 'wo', english: 'where' },
          { german: 'woher', english: 'from where' },
          { german: 'wohin', english: 'to where' },
          { german: 'wie', english: 'how' },
          { german: 'warum', english: 'why' },
          { german: 'wie alt', english: 'how old' },
          { german: 'wie oft', english: 'how often' },
          { german: 'welche Sprachen', english: 'which languages' },
          { german: 'welche Hobbys', english: 'which hobbies' },
          { german: 's Hobby, -s', english: 'hobby' },
          { german: 'ja', english: 'yes' },
          { german: 'nein', english: 'no' }
        ]
      },
      {
        name: "E1: Ich und die anderen (Teil 2)",
        words: [
          { german: 'e Leute', english: 'people' },
          { german: 'e Menschen', english: 'people1' },
          { german: 'r Mensch, -en', english: 'human' },
          { german: 's Kind, -er', english: 'child' },
          { german: 'e Frau, -en', english: 'woman; wife; lady' },
          { german: 'r Mann, Männer', english: 'man; husband' },
          { german: 'r Herr, -en', english: 'gentleman' },
          { german: 'jetzt', english: 'now' },
          { german: 'r Familienstand', english: 'marital/family status' },
          { german: 'Single', english: 'single - young' },
          { german: 'ledig', english: 'single - "older"' },
          { german: 'verheiratet', english: 'married' },
          { german: 'geschieden', english: 'divorced' },
          { german: 'verwitwet', english: 'widowed' },
          { german: 'von Beruf', english: 'by profession' },
          { german: 'arbeiten als', english: 'work as' },
          { german: 'arbeiten bei', english: 'work at' },
          { german: 'e Firma, Firmen', english: 'company' },
          { german: 'r Beruf, -e', english: 'profession' },
          { german: 'r Ingenieur, -e', english: 'engineer' },
          { german: 'e Ingenieurin, -nen', english: 'female engineer' },
          { german: 'r Lehrer, -', english: 'teacher' },
          { german: 'e Lehrerin, -nen', english: 'female teacher' },
          { german: 'r Schulleiter, -', english: 'school principal' },
          { german: 'e Schulleiterin, -nen', english: 'female school principal' },
          { german: 'r Erzieher, -', english: 'educator' },
          { german: 'e Erzieherin, -nen', english: 'female educator' },
          { german: 'r Betreuer, -', english: 'caregiver1' },
          { german: 'e Betreuerin, -nen', english: 'female caregiver2' },
          { german: 'e Hausfrau, -en', english: 'housewife' },
          { german: 'r Programmierer, -', english: 'programmer' },
          { german: 'e Programmiererin, -nen', english: 'female programmer' },
          { german: 'r Automechaniker, -', english: 'car mechanic' },
          { german: 'r Arzt, Ärzte', english: 'doctor' },
          { german: 'e Ärztin, -nen', english: 'female doctor' },
          { german: 'r Schüler, -', english: 'student' },
          { german: 'e Schülerin, -nen', english: 'female student' },
          { german: 'e Schule, -n', english: 'school' },
          { german: 'besuchen', english: 'to visit, attend' },
          { german: 'e Grundschule, -n', english: 'primary school' },
          { german: 'zur Zeit', english: 'currently' },
          { german: 'momentan', english: 'currently1' },
          { german: 'klein', english: 'small' },
          { german: 'groß', english: 'big' },
          { german: 's Hobby, -s', english: 'hobby' },
          { german: 'lesen', english: 'to read' },
          { german: 'laufen', english: 'to run; = joggen' },
          { german: 'Gitarre spielen', english: 'to play the guitar' },
          { german: 'Schlagzeug spielen', english: 'to play the drums' },
          { german: 'Klavier spielen', english: 'to play the piano' },
          { german: 'Geige spielen', english: 'to play the violin' },
          { german: 'Federball spielen', english: 'to play badminton' },
          { german: 'machen', english: 'to do' },
          { german: 'gern', english: 'gladly' },
          { german: 'Was machst du gern?', english: 'What do you like to do?' },
          { german: 'allein', english: 'alone' },
          { german: 'liegen', english: 'to lie' },
          { german: 'Wo liegt Bern?', english: 'Where is Bern located?' },
          { german: 'Herr Mayer', english: 'Mr. Mayer' },
          { german: 'Frau Mayer', english: 'Mrs. Mayer' },
          { german: 'tanzen', english: 'to dance' },
          { german: 'gut', english: 'good' },
          { german: 'sehr gut', english: 'very good' },
          { german: 'sehr', english: 'very' },
          { german: 'sehr gern', english: 'very gladly' },
          { german: 'noch', english: 'still' },
          { german: 'man', english: 'people in general' },
          { german: 'noch ein bisschen', english: 'a bit more' },
          { german: 'ein bisschen', english: 'a little' },
          { german: 'hier', english: 'here' },
          { german: 'dort', english: 'there' },
          { german: 'reisen', english: 'to travel' },
          { german: 'viel', english: 'much, a lot' },
          { german: 'oft', english: 'often' },
          { german: 'auch', english: 'also' },
          { german: 'r Junge, -n', english: 'boy' },
          { german: 's Mädchen, -', english: 'girl' },
          { german: 'studieren', english: 'to study' },
          { german: 'Jura', english: 'law' },
          { german: 'Medizin', english: 'medicine' },
          { german: 'unterwegs', english: 'on the way' },
          { german: 'Sport treiben', english: 'to do sports' },
          { german: 'Sport machen', english: 'to do sports2' },
          { german: 'Das sind', english: 'These are ...' },
          { german: 'leben', english: 'to live' }
        ]
      },
      {
        name: "E1: Ich und die anderen (Teil 3)",
        words: [
          { german: 'ein paar', english: 'a few' },
          { german: 'r Freiwillige, -n', english: 'volunteer' },
          { german: 'e Freiwillige, -n', english: 'female volunteer' },
          { german: 'ins Fitnessstudio gehen', english: 'to go to the gym' },
          { german: 'Filme gucken', english: 'to watch movies' },
          { german: 'Serien gucken', english: 'to watch series' },
          { german: 'zocken', english: 'to play video games' },
          { german: 'Computerspiele spielen', english: 'to play video games' },
          { german: 'kochen', english: 'to cook' },
          { german: 'backen', english: 'to bake' },
          { german: 'trainieren', english: 'to train' },
          { german: 'Ich trainiere Basketball.', english: 'I train basketball' },
          { german: 'Frisbee spielen', english: 'to play frisbee' },
          { german: 'Federball spielen', english: 'to play badminton' },
          { german: 'Wasserball spielen', english: 'to play water polo' },
          { german: 'Handball spielen', english: 'to play handball' },
          { german: 'Volleyball spielen', english: 'to play volleyball' },
          { german: 'Fußball spielen', english: 'to play football/soccer' },
          { german: 'mit dem Hund spazieren gehen', english: 'to walk the dog' },
          { german: 'Musik hören', english: 'to listen to music' },
          { german: 'schwimmen', english: 'to swim' },
          { german: 'tauchen', english: 'to dive' },
          { german: 'fotografieren', english: 'to photograph' },
          { german: 'Fotos machen', english: 'to take photos' },
          { german: 'malen', english: 'to paint' },
          { german: 'singen', english: 'to sing' },
          { german: 'im Chor singen', english: 'to sing in a choir' },
          { german: 'tanzen', english: 'to dance' },
          { german: 'reisen', english: 'to travel' },
          { german: 'faulenzen', english: 'to laze around' },
          { german: 'faul', english: 'lazy' },
          { german: 'reiten', english: 'to ride (horse)' },
          { german: 'zelten', english: 'to camp' },
          { german: 'zeichnen', english: 'to draw' },
          { german: 'Ski fahren', english: 'to ski' },
          { german: 'mit dem Fahrrad fahren', english: 'to ride a bicycle' },
          { german: 'Fahrrad fahren', english: 'to cycle' },
          { german: 'mit dem E-Scooter fahren', english: 'to ride an electric scooter' },
          { german: 'laufen', english: 'to run' },
          { german: 'joggen', english: 'to jog' },
          { german: 'Pfadfinder/Pfadfinderin sein', english: 'to be a scout' },
          { german: 'r Pfadfinder, -', english: 'scout' },
          { german: 'Ich bin Pfadfinderin.', english: 'I am a scout.' },
          { german: 'plaudern', english: 'to chat' },
          { german: 'basteln', english: 'to craft creatively' },
          { german: 'wandern', english: 'to hike in mountains, hills' },
          { german: 'bummeln', english: 'to stroll in the city' },
          { german: 'e Geige, -n', english: 'violin' },
          { german: 'sammeln', english: 'to collect' },
          { german: 'lesen', english: 'to read' },
          { german: 'Bücher lesen', english: 'to read books' },
          { german: 'Tischtennis spielen', english: 'to play table tennis' },
          { german: 'sitzen', english: 'to sit' },
          { german: 'fahren', english: 'to drive, ride' },
          { german: 'schlafen', english: 'to sleep' },
          { german: 'kaufen', english: 'to buy' },
          { german: 'verkaufen', english: 'to sell' },
          { german: 's Auto, -s', english: 'car' }
        ]
      },
      {
        name: "E1: Länder - Nationalitäten - Sprachen",
        words: [
          { german: 'Slowenien', english: 'Slovenia' },
          { german: 'r Slowene, -n', english: 'Slovenian (male)' },
          { german: 'e Slowenin, -nen', english: 'Slovenian (female)' },
          { german: 'Slowenisch', english: 'Slovenian (language)' },
          { german: 'Deutschland', english: 'Germany' },
          { german: 'r Deutsche, -n', english: 'German (male)' },
          { german: 'e Deutsche, -n', english: 'German (female)' },
          { german: 'Österreich', english: 'Austria' },
          { german: 'r Österreicher, -', english: 'Austrian (male)' },
          { german: 'e Österreicherin, -nen', english: 'Austrian (female)' },
          { german: 'Wien', english: 'Vienna' },
          { german: 'e Schweiz', english: 'Switzerland' },
          { german: 'r Schweizer, -', english: 'Swiss (male)' },
          { german: 'e Schweizerin, -nen', english: 'Swiss (female)' },
          { german: 'Rätoromanisch', english: 'Romansh' },
          { german: 'Italien', english: 'Italy' },
          { german: 'Rom', english: 'Rome' },
          { german: 'Mailand', english: 'Milan' },
          { german: 'r Italiener, -', english: 'Italian (male)' },
          { german: 'e Italienerin, -nen', english: 'Italian (female)' },
          { german: 'Italienisch', english: 'Italian (language)' },
          { german: 'Frankreich', english: 'France' },
          { german: 'r Franzose, -n', english: 'Frenchman' },
          { german: 'e Französin, -nen', english: 'Frenchwoman' },
          { german: 'Französisch', english: 'French (language)' },
          { german: 'Spanien', english: 'Spain' },
          { german: 'r Spanier, -', english: 'Spaniard (male)' },
          { german: 'e Spanierin, -nen', english: 'Spaniard (female)' },
          { german: 'Spanisch', english: 'Spanish (language)' },
          { german: 'Portugal', english: 'Portugal' },
          { german: 'Lissabon', english: 'Lisbon' },
          { german: 'r Portugiese, -n', english: 'Portuguese (male)' },
          { german: 'e Portugiesin, -nen', english: 'Portuguese (female)' },
          { german: 'Portugiesisch', english: 'Portuguese (language)' },
          { german: 'Kroatien', english: 'Croatia' },
          { german: 'r Kroate, -n', english: 'Croatian (male)' },
          { german: 'e Kroatin, -nen', english: 'Croatian (female)' },
          { german: 'Griechenland', english: 'Greece' },
          { german: 'r Grieche, -n', english: 'Greek (male)' },
          { german: 'e Griechin, -nen', english: 'Greek (female)' },
          { german: 'Griechisch', english: 'Greek (language)' },
          { german: 'e Türkei', english: 'Turkey' },
          { german: 'r Türke, -n', english: 'Turk (male)' },
          { german: 'e Türkin, -nen', english: 'Turk (female)' },
          { german: 'Türkisch', english: 'Turkish (language)' },
          { german: 'Irland', english: 'Ireland' },
          { german: 'r Ire, -n', english: 'Irishman' },
          { german: 'e Irin, -nen', english: 'Irishwoman' },
          { german: 'Großbritannien', english: 'Great Britain' },
          { german: 'r Brite, -n', english: 'Briton (male)' },
          { german: 'e Britin, -nen', english: 'Briton (female)' },
          { german: 'Englisch', english: 'English (language)' },
          { german: 'England', english: 'England' },
          { german: 'r Engländer, -', english: 'Englishman' },
          { german: 'e Engländerin, -nen', english: 'Englishwoman' },
          { german: 'Norwegen', english: 'Norway' },
          { german: 'r Norweger, -n', english: 'Norwegian (male)' },
          { german: 'e Norwegerin, -nen', english: 'Norwegian (female)' },
          { german: 'Norwegisch', english: 'Norwegian (language)' },
          { german: 'Schweden', english: 'Sweden' },
          { german: 'r Schwede, -n', english: 'Swede (male)' },
          { german: 'e Schwedin, -nen', english: 'Swede (female)' },
          { german: 'Schwedisch', english: 'Swedish (language)' },
          { german: 'Dänemark', english: 'Denmark' },
          { german: 'r Däne, -n', english: 'Dane (male)' },
          { german: 'e Dänin, -nen', english: 'Dane (female)' },
          { german: 'Dänisch', english: 'Danish (language)' },
          { german: 'e Niederlande', english: 'Netherlands' },
          { german: 'r Niederländer, -', english: 'Dutchman' },
          { german: 'e Niederländerin, -nen', english: 'Dutchwoman' },
          { german: 'Niederländisch', english: 'Dutch (language)' },
          { german: 'Polen', english: 'Poland' },
          { german: 'r Pole, -n', english: 'Pole (male)' },
          { german: 'e Polin, -nen', english: 'Pole (female)' },
          { german: 'Polnisch', english: 'Polish (language)' },
          { german: 'Tschechien', english: 'Czech Republic' },
          { german: 'r Tscheche, -n', english: 'Czech (male)' },
          { german: 'e Tschechin, -nen', english: 'Czech (female)' },
          { german: 'Tschechisch', english: 'Czech (language)' },
          { german: 'e Slowakei', english: 'Slovakia' },
          { german: 'r Slowake, -n', english: 'Slovak (male)' },
          { german: 'e Slowakin, -nen', english: 'Slovak (female)' },
          { german: 'Slowakisch', english: 'Slovak (language)' },
          { german: 'e USA', english: 'USA' },
          { german: 'r Amerikaner, -', english: 'American (male)' },
          { german: 'e Amerikanerin, -nen', english: 'American (female)' },
          { german: 'Russland', english: 'Russia' },
          { german: 'r Russe, -n', english: 'Russian (male)' },
          { german: 'e Russin, -nen', english: 'Russian (female)' },
          { german: 'Russisch', english: 'Russian (language)' },
          { german: 'Ungarn', english: 'Hungary' },
          { german: 'r Ungar, -n', english: 'Hungarian (male)' },
          { german: 'e Ungarin, -nen', english: 'Hungarian (female)' },
          { german: 'Ungarisch', english: 'Hungarian (language)' }
        ]
      }
    ],
    'E2': [
      {
        name: "E2: Schulsachen",
        words: [
          { german: 'der Schulalltag', english: 'school routine' },
          { german: 'die Schulsachen', english: 'school supplies' },
          { german: 'der Gegenstand, Gegenstände', english: 'object, concrete item' },
          { german: 'der Schulranzen, -', english: 'school bag' },
          { german: 'der Kuli, -s', english: 'ballpoint pen' },
          { german: 'der Bleistift, -e', english: 'pencil' },
          { german: 'der Buntstift, -e', english: 'colored pencil' },
          { german: 'der Filzstift, -e', english: 'felt-tip pen' },
          { german: 'der Radiergummi, -s', english: 'eraser' },
          { german: 'der Zirkel, -', english: 'compass' },
          { german: 'der Lautsprecher, -', english: 'speaker' },
          { german: 'der Kugelschreiber, -', english: 'ballpoint pen1' },
          { german: 'der Klebestift, -e', english: 'glue stick' },
          { german: 'der Kleber, -', english: 'glue' },
          { german: 'der Spitzer, -', english: 'pencil sharpener' },
          { german: 'der Tafelwischer, -', english: 'blackboard eraser' },
          { german: 'der Füller, -', english: 'fountain pen' },
          { german: 'der Tintenlöscher, -', english: 'ink eraser' },
          { german: 'der Tisch, -e', english: 'table' },
          { german: 'der Stuhl, Stühle', english: 'chair' },
          { german: 'der Schreibtisch, -e', english: 'desk' },
          { german: 'der Beamer, -', english: 'projector' },
          { german: 'der Bildschirm, -e', english: 'screen' },
          { german: 'der Schlüssel, -', english: 'key' },
          { german: 'der Computer, -', english: 'computer' },
          { german: 'der Rechner, -', english: 'computer1' },
          { german: 'der Taschenrechner, -', english: 'calculator' },
          { german: 'der Pantoffel, -n', english: 'slipper' },
          { german: 'der Hausschuh, -e', english: 'slipper1' },
          { german: 'der Lehrer, -', english: 'teacher, professor' },
          { german: 'der Klassenlehrer, -', english: 'class teacher' },
          { german: 'der Schüler, -', english: 'student' },
          { german: 'der Mitschüler, -', english: 'classmate' },
          { german: 'der Mitbewohner, -', english: 'roommate' },
          { german: 'der Freund, -e', english: 'friend' },
          { german: 'die Schule, -n', english: 'school' },
          { german: 'die Grundschule, -n', english: 'primary school' },
          { german: 'die Klasse, -n', english: 'class, grade' },
          { german: 'Ich bin in der ersten Klasse', english: 'I am in the first grade' },
          { german: 'die Tafel, -n', english: 'blackboard' },
          { german: 'die Landkarte, -n', english: 'map' },
          { german: 'die Frage, -n', english: 'question' },
          { german: 'die Antwort, -en', english: 'answer' },
          { german: 'die Sache, -n', english: 'thing, item1' },
          { german: 'die Schultasche, -n', english: 'school bag1' },
          { german: 'die Schere, -n', english: 'scissors' },
          { german: 'die Tastatur, -en', english: 'keyboard' },
          { german: 'die Maus, Mäuse', english: 'mouse; computer mouse' },
          { german: 'die Wasserfarbe, -n', english: 'watercolor' },
          { german: 'die Stofftüte, -n', english: 'fabric bag' },
          { german: 'die Tüte, -n', english: 'bag' },
          { german: 'die Plastiktüte, -n', english: 'plastic bag' },
          { german: 'die Mappe, -n', english: 'folder' },
          { german: 'die Übung, -en', english: 'exercise' },
          { german: 'die Aufgabe, -n', english: 'task' },
          { german: 'die Hausaufgabe, -n', english: 'homework' },
          { german: 'die Tür, -en', english: 'door' },
          { german: 'die Uhr, -en', english: 'clock, watch; or 6:00 PM' },
          { german: 'die Stunde, -n', english: 'hour = 60 minutes; 45 minutes' },
          { german: 'die Klingel, -n', english: 'school bell' },
          { german: 'die Lehrerin, -nen', english: 'female teacher, professor' },
          { german: 'die Klassenlehrerin, -nen', english: 'female class teacher' },
          { german: 'die Schülerin, -nen', english: 'female student' },
          { german: 'die Mitschülerin, -nen', english: 'female classmate' },
          { german: 'die Mitbewohnerin, -nen', english: 'female roommate' },
          { german: 'die Freundin, -nen', english: 'female friend' },
          { german: 'das Ding, -e', english: 'thing, item2' },
          { german: 'das Heft, -e', english: 'notebook' },
          { german: 'das Lineal, -e', english: 'ruler' },
          { german: 'das Klassenzimmer, -', english: 'classroom' },
          { german: 'das Zimmer, -', english: 'room' },
          { german: 'das Gymnasium, Gymnasien', english: 'high school' },
          { german: 'das Schulfach, die Schulfächer', english: 'school subject; e.g., Math, Biology, History' },
          { german: 'z. B.', english: 'e.g.' },
          { german: 'usw.', english: 'etc.' },
          { german: 'das Buch, Bücher', english: 'book' },
          { german: 'das Kursbuch, Kursbücher', english: 'textbook' },
          { german: 'das Arbeitsbuch, Arbeitsbücher', english: 'workbook' },
          { german: 'das Wörterbuch, Wörterbücher', english: 'dictionary' },
          { german: 'das Arbeitsblatt, Arbeitsblätter', english: 'worksheet' },
          { german: 'das Foto, -s', english: 'photograph' },
          { german: 'das Bild, -er', english: 'picture' },
          { german: 'das Papier, -e', english: 'paper' },
          { german: 'das Fenster, -', english: 'window' },
          { german: 'das Licht, -er', english: 'light' },
          { german: 'das Taschentuch, -tücher', english: 'handkerchief' },
          { german: 'das Poster, -', english: 'poster' },
          { german: 'das Handy, -s', english: 'mobile phone' },
          { german: 'das Federmäppchen, -', english: 'pencil case' },
          { german: 'das Beispiel, -e', english: 'example' }
        ]
      },
      {
        name: "E2: Schulfächer",
        words: [
          { german: 'das Schulfach, Schulfächer', english: 'school subject' },
          { german: 'Mathe', english: 'math' },
          { german: 'Mathematik', english: 'mathematics' },
          { german: 'Slowenisch', english: 'Slovenian (language)' },
          { german: 'Deutsch', english: 'German (language)' },
          { german: 'Latein', english: 'Latin' },
          { german: 'Spanisch', english: 'Spanish (language)' },
          { german: 'Englisch', english: 'English (language)' },
          { german: 'Chemie', english: 'chemistry' },
          { german: 'Physik', english: 'physics' },
          { german: 'Biologie', english: 'biology' },
          { german: 'Geographie', english: 'geography' },
          { german: 'Erdkunde', english: 'geography1' },
          { german: 'Geschichte', english: 'history; story' },
          { german: 'Kunst', english: 'art' },
          { german: 'Informatik', english: 'computer science' },
          { german: 'Religion und Kultur', english: 'religion and culture' },
          { german: 'Sport', english: 'sports' },
          { german: 'Musik', english: 'music' },
          { german: 'Philosophie', english: 'philosophy' },
          { german: 'Psychologie', english: 'psychology' },
          { german: 'der Test, -s', english: 'test' },
          { german: 'die Prüfung, -en', english: 'exam' },
          { german: 'das Abitur', english: 'matura - Germany' },
          { german: 'die Matura', english: 'matura - Austria, Switzerland' },
          { german: 'das Pflichtfach, Pflichtfächer', english: 'compulsory subject' },
          { german: 'das Wahlfach, Wahlfächer', english: 'elective subject' },
          { german: 'die Lieblingsstunde, -n', english: 'favorite lesson' },
          { german: 'die Freistunde, -n', english: 'free period' },
          { german: 'die Lernstunde, -n', english: 'study hour' },
          { german: 'die goldene Lernstunde, -n', english: 'golden study hour' },
          { german: 'die Pause, -n', english: 'break; pause' },
          { german: 'die große Pause', english: '"long" break' },
          { german: 'die Jause', english: 'snack - Austria' },
          { german: 'das Pausenbrot', english: 'snack' },
          { german: 'das Frühstück', english: 'breakfast' },
          { german: 'das Mittagessen', english: 'lunch' },
          { german: 'das Abendessen', english: 'dinner' },
          { german: 'dauern', english: 'to last' },
          { german: 'Die Pause dauert fünf Minuten', english: 'The break lasts five minutes' },
          { german: 'der Unterricht', english: 'class, lesson' },
          { german: 'unterrichten', english: 'to teach' },
          { german: 'der Stundenplan, Stundenpläne', english: 'timetable' },
          { german: 'der Nachhilfeunterricht', english: 'tutoring' },
          { german: 'der Wettbewerb, -e', english: 'competition' },
          { german: 'die Vorbereitung auf/für', english: 'preparation for' },
          { german: 'die Chorprobe, -n', english: 'choir rehearsal' },
          { german: 'die AG, -s', english: 'club, extracurricular activity' },
          { german: 'Wie oft habt ihr', english: 'How often do you have' },
          { german: 'pro Woche', english: 'per week' },
          { german: 'einmal, zweimal, dreimal, viermal, fünfmal', english: 'once, twice, three times, four times, five times' },
          { german: 'Wir haben Slowenisch viermal pro Woche.', english: 'We have Slovenian four times a week.' },
          { german: 'Wie viele Stunden Slowenisch hast du?', english: 'How many hours of Slovenian do you have?' },
          { german: 'Ich habe vier Stunden Slowenisch pro Woche.', english: 'I have four hours of Slovenian per week.' },
          { german: 'Was macht ihr bei/in', english: 'What do you do at/in' },
          { german: 'üben', english: 'to practice' },
          { german: 'übersetzen', english: 'to translate' },
          { german: 'turnen', english: 'to do gymnastics' },
          { german: 'wiederholen', english: 'to repeat' },
          { german: 'der Wortschatz', english: 'vocabulary' },
          { german: 'Übungen machen', english: 'to do exercises' },
          { german: 'diskutieren', english: 'to discuss' },
          { german: 'erzählen', english: 'to tell, narrate' },
          { german: 'experimentieren', english: 'to experiment' },
          { german: 'mit', english: 'with' },
          { german: 'schreiben', english: 'to write' }
        ]
      },
      {
        name: "E2: Die Zeit",
        words: [
          { german: 'DIE Zeit, -en', english: 'time' },
          { german: 's Jahr, -e', english: 'year' },
          { german: 'e Jahreszeit, -en', english: 'season' },
          { german: 'r Monat, -e', english: 'month' },
          { german: 'e Woche, -n', english: 'week' },
          { german: 'r Tag, -e', english: 'day' },
          { german: 'e Stunde, -n', english: 'hour' },
          { german: 'e Minute, -n', english: 'minute' },
          { german: 'e Sekunde, -n', english: 'second' },
          { german: 'r Herbst, -e', english: 'autumn' },
          { german: 'r Winter, -', english: 'winter' },
          { german: 'r Frühling, -e', english: 'spring' },
          { german: 'r Sommer, -', english: 'summer' },
          { german: 's Wochenende, Wochenenden', english: 'weekend; Saturday + Sunday' },
          { german: 'r Frühling', english: 'March + April + May' },
          { german: 'r Sommer', english: 'June + July + August' },
          { german: 'r Herbst', english: 'September + October + November' },
          { german: 'r Winter', english: 'December + January + February' },
          { german: 'im Januar', english: 'in January' },
          { german: 'im März', english: 'in March' },
          { german: 'im Mai', english: 'in May' },
          { german: 'im Winter', english: 'in winter' },
          { german: 'im Frühling', english: 'in spring' },
          { german: 'im Sommer', english: 'in summer' },
          { german: 'im Herbst', english: 'in autumn' },
          { german: 'am Wochenende', english: 'on the weekend' },
          { german: 'unter der Woche', english: 'during the week' },
          { german: 'r Montag', english: 'Monday' },
          { german: 'r Dienstag', english: 'Tuesday' },
          { german: 'r Mittwoch', english: 'Wednesday' },
          { german: 'r Donnerstag', english: 'Thursday' },
          { german: 'r Freitag', english: 'Friday' },
          { german: 'r Samstag', english: 'Saturday' },
          { german: 'r Sonntag', english: 'Sunday' },
          { german: 'jeden Tag', english: 'every day' },
          { german: 'jeden Montag = montags', english: 'every Monday' },
          { german: 'jeden Dienstag = dienstags', english: 'every Tuesday' },
          { german: 'r Morgen', english: 'morning' },
          { german: 'r Vormittag', english: 'forenoon' },
          { german: 'r Mittag', english: 'noon' },
          { german: 'r Nachmittag', english: 'afternoon' },
          { german: 'r Abend', english: 'evening' },
          { german: 'e Nacht, Nächte', english: 'night' },
          { german: 'e Mitternacht', english: 'midnight' },
          { german: 'am Morgen, morgens', english: 'in the morning' },
          { german: 'am Vormittag, vormittags', english: 'in the forenoon' },
          { german: 'am Mittag, mittags', english: 'at noon' },
          { german: 'am Nachmittag, nachmittags', english: 'in the afternoon' },
          { german: 'am Abend, abends', english: 'in the evening' },
          { german: 'in der Nacht, nachts', english: 'at night' },
          { german: 'um neun Uhr', english: 'at nine o’clock' },
          { german: 'um Viertel nach sechs', english: 'at quarter past six' },
          { german: 'um Viertel vor fünf', english: 'at quarter to five' },
          { german: 'um halb zwölf', english: 'at half past eleven' },
          { german: 'Wie spät ist es?', english: 'What time is it?' },
          { german: 'Wie viel Uhr ist es?', english: 'What time is it? 2' },
          { german: 'r Werktag', english: 'weekday' },
          { german: 'werktags', english: 'on weekdays' },
          { german: 's Wochenende, -n', english: 'weekend' },
          { german: 'tagsüber', english: 'during the day' },
          { german: 'nachts', english: 'at night' },
          { german: 'am Wochenende', english: 'on the weekend' },
          { german: 'in der Woche', english: 'during the week 1' },
          { german: 'unter der Woche', english: 'during the week 2' },
          { german: 'in den Ferien', english: 'during the holidays' },
          { german: 'im Unterricht', english: 'in class' },
          { german: 'viel Zeit', english: 'a lot of time' },
          { german: 'wenig Zeit', english: 'little time' },
          { german: 'keine Zeit', english: 'no time' },
          { german: 'jeden Tag', english: 'every day 1' },
          { german: 'täglich', english: 'every day 2' },
          { german: 'jeden Monat', english: 'every month 1' },
          { german: 'monatlich', english: 'every month 2' },
          { german: 'jedes Jahr', english: 'every year 1' },
          { german: 'jährlich', english: 'every year 2' },
          { german: 'jeden Dienstag', english: 'every Tuesday 1' },
          { german: 'dienstags', english: 'every Tuesday 2' },
          { german: 'jeden Mittwoch', english: 'every Wednesday 1' },
          { german: 'mittwochs', english: 'every Wednesday 2' },
          { german: 'jeden Nachmittag', english: 'every afternoon 1' },
          { german: 'nachmittags', english: 'every afternoon 2' },
          { german: 'jeden Morgen', english: 'every morning 1' },
          { german: 'morgens', english: 'every morning 2' },
          { german: 'vorgestern', english: 'the day before yesterday' },
          { german: 'gestern', english: 'yesterday' },
          { german: 'heute', english: 'today' },
          { german: 'morgen', english: 'tomorrow' },
          { german: 'übermorgen', english: 'the day after tomorrow' },
          { german: 'jetzt', english: 'now 1' },
          { german: 'nun', english: 'now 2' },
          { german: 'nie', english: 'never' },
          { german: 'selten', english: 'rarely' },
          { german: 'manchmal', english: 'sometimes 1' },
          { german: 'ab und zu', english: 'sometimes 2' },
          { german: 'oft', english: 'often 1' },
          { german: 'häufig', english: 'often 2' },
          { german: 'fast immer', english: 'almost always' },
          { german: 'immer', english: 'always' },
          { german: 'normalerweise', english: 'usually' },
          { german: 'e Freizeit', english: 'free time' },
          { german: 'in den Winterferien', english: 'during winter holidays' },
          { german: 'in den Herbstferien', english: 'during autumn holidays' },
          { german: 'in den Sommerferien', english: 'during summer holidays' },
          { german: 'e Ferien', english: 'holidays + plural!' }
        ]
      }
    ],
    'E3': [
      {
        name: "E3: Räume im Haus",
        words: [
          { german: "s Haus, Häuser", english: "house" },
          { german: "Ich bin zu Hause.", english: "I am at home." },
          { german: "Ich gehe nach Hause.", english: "I am going home." },
          { german: "e Wohnung, -en", english: "apartment" },
          { german: "s Erdgeschoss", english: "ground floor" },
          { german: "s Zimmer, -", english: "room" },
          { german: "r Raum, Räume", english: "1. space / 2. room" },
          { german: "s Wohnzimmer, -", english: "living room" },
          { german: "s Schlafzimmer, -", english: "bedroom" },
          { german: "s Badezimmer, -", english: "bathroom" },
          { german: "s Klo, -s / e Toilette, die Toiletten", english: "toilet" },
          { german: "s Arbeitszimmer, -", english: "study" },
          { german: "s Kinderzimmer, -", english: "children’s room" },
          { german: "r Dachboden, e Dachböden", english: "attic" },
          { german: "r Keller, -", english: "basement" },
          { german: "e Stiege, -n (Ö)", english: "stair1" },
          { german: "e Treppe, -n", english: "stair2" },
          { german: "e Stufe, -n", english: "step" },
          { german: "s Treppenhaus, die Treppenhäuser", english: "staircase" },
          { german: "e Etage, die Etagen / der Stock", english: "floor (storey)" },
          { german: "s Esszimmer", english: "dining room" },
          { german: "s Gästezimmer, -", english: "guest room" },
          { german: "e Küche, -n", english: "kitchen" },
          { german: "e Garage, -n", english: "garage" },
          { german: "e Terrasse, die Terrassen", english: "terrace" },
          { german: "r Balkon, die Balkone", english: "balcony" },
          { german: "r Flur, die Flure", english: "1. hallway / 2. entrance hall" },
          { german: "r Garten, Gärten", english: "garden" }
        ]
      },
      {
        name: "E3: Das Möbel und die Einrichtung",
        words: [
          { german: "s Möbel", english: "furniture" },
          { german: "e Einrichtung (-en)", english: "1. furniture, equipment / 2. institution" },
          { german: "s Dach (Dächer)", english: "roof" },
          { german: "r Boden (Böden)", english: "floor" },
          { german: "e Wand (Wände)", english: "wall" },
          { german: "e Tür (-en)", english: "door" },
          { german: "s Fenster (-)", english: "window" },
          { german: "e Decke (-n)", english: "1. ceiling / 2. blanket" },
          { german: "s Licht (-er)", english: "1. light / 2. illumination" },
          { german: "e Steckdose (-n)", english: "power socket" },
          { german: "r Lichtschalter (-)", english: "light switch" },
          { german: "s Bett (-en)", english: "bed" },
          { german: "s Doppelbett (-en)", english: "double bed" },
          { german: "r Nachttisch (-e)", english: "nightstand" },
          { german: "e Nachttischlampe (-n)", english: "bedside lamp" },
          { german: "r Schrank (Schränke)", english: "wardrobe, cabinet" },
          { german: "r Kleiderschrank (-schränke)", english: "clothes wardrobe" },
          { german: "s Polster (-) = s Kissen (-)", english: "pillow" },
          { german: "s Einzelbett (-en)", english: "single bed" },
          { german: "s Stockbett (-en) = s Etagenbett (-en)", english: "bunk bed" },
          { german: "r Schreibtisch (-e)", english: "desk" },
          { german: "s Regal (-e)", english: "shelf" },
          { german: "e Schublade (-n)", english: "drawer" },
          { german: "e Kommode (-n)", english: "chest of drawers" },
          { german: "s Bild (-er)", english: "picture" },
          { german: "s Waschbecken (-)", english: "sink" },
          { german: "r Wasserhahn (-hähne)", english: "faucet" },
          { german: "r Spiegel (-)", english: "mirror" },
          { german: "e Dusche (-n)", english: "shower" },
          { german: "e Badewanne (-n)", english: "bathtub" },
          { german: "e Waschmaschine (-n)", english: "washing machine" },
          { german: "r Teppich (-e)", english: "carpet" },
          { german: "s Bücherregal (-e)", english: "bookshelf" },
          { german: "r Couchtisch (-e)", english: "coffee table" },
          { german: "e Couch (-s/-en)", english: "couch" },
          { german: "r Sessel (-)", english: "armchair" },
          { german: "s Sofa (-s)", english: "sofa" },
          { german: "r Fernseher (-)", english: "television" },
          { german: "e Stehlampe (-n)", english: "floor lamp" },
          { german: "r Esstisch (-e)", english: "dining table" },
          { german: "r Stuhl (Stühle)", english: "chair" },
          { german: "e Vase (-n)", english: "vase" },
          { german: "r Vorhang (Vorhänge)", english: "curtain (1)" },
          { german: "e Gardine (-n)", english: "curtain (2)" },
          { german: "r Herd (-e)", english: "stove" },
          { german: "r Gasherd (-e)", english: "gas stove" },
          { german: "r Elektroherd (-e)", english: "electric stove" },
          { german: "r Backofen (-öfen)", english: "oven" },
          { german: "r Küchenschrank (-schränke)", english: "kitchen cabinet" },
          { german: "r Kühlschrank (-schränke)", english: "refrigerator" },
          { german: "e Spülmaschine (-n)", english: "dishwasher" },
          { german: "e Spüle (-n), s Spülbecken (-)", english: "kitchen sink" }
        ]
      },
      {
        name: "E3: Possessivartikel",
        words: [
          { german: "mein-", english: "my-" },
          { german: "dein-", english: "your-" },
          { german: "sein-", english: "his-" },
          { german: "ihr-", english: "her - singular" },
          { german: "unser-", english: "our" },
          { german: "euer/eur-", english: "your-" },
          { german: "ihr-", english: "their - plural" },
          { german: "Ihr-", english: "Your-" },
          { german: "mein Haus", english: "my house" },
          { german: "dein Heft", english: "your notebook" },
          { german: "seine Tasche", english: "his bag" },
          { german: "Ich sehe seinen Hund.", english: "I see her dog." },
          { german: "eure Bücher", english: "your books" },
          { german: "euer Füller", english: "your fountain pen" },
          { german: "Ihre Katze", english: "Your cat" }
        ]
      },
      {
        name: "E3: Wichtige Adjektive",
        words: [
          { german: "groß (velik) ≠ klein (majhen)", english: "big ≠ small" },
          { german: "dunkel (temen) ≠ hell (svetel)", english: "dark ≠ light" },
          { german: "teuer (drag) ≠ billig, günstig, preiswert (poceni, ugoden)", english: "expensive ≠ cheap, affordable" },
          { german: "neu (nov) ≠ alt (star)", english: "new ≠ old" },
          { german: "laut (glasen) ≠ leise (tih)", english: "loud ≠ quiet" },
          { german: "schön (lep) ≠ hässlich (grd)", english: "beautiful ≠ ugly" },
          { german: "lang (dolg) ≠ kurz (kratek)", english: "long ≠ short" },
          { german: "schnell (hiter) ≠ langsam (počasen)", english: "fast ≠ slow" },
          { german: "kühl (hladen) ≠ warm (topel)", english: "cool ≠ warm" },
          { german: "kalt (mrzel) ≠ heiß (vroč)", english: "cold ≠ hot" },
          { german: "hoch (visok) ≠ niedrig (nizek)", english: "high ≠ low" },
          { german: "spät (pozen) ≠ früh (zgoden)", english: "late ≠ early" },
          { german: "wichtig (pomemben) ≠ unwichtig (nepomemben)", english: "important ≠ unimportant" },
          { german: "einfach (preprost) ≠ kompliziert, schwierig (zapleten, težaven)", english: "simple ≠ complicated, difficult" },
          { german: "leicht (lahek) ≠ schwer (težak)", english: "light ≠ heavy" },
          { german: "falsch (napačen) ≠ richtig (pravilen)", english: "wrong ≠ correct" },
          { german: "jung (mlad) ≠ alt (star)", english: "young ≠ old" },
          { german: "interessant (zanimiv) ≠ langweilig (dolgočasen)", english: "interesting ≠ boring" },
          { german: "altmodisch (staromoden) ≠ modern (moderen)", english: "old-fashioned ≠ modern" },
          { german: "ordentlich (urejen, pospravljen) ≠ unordentlich, chaotisch (neurejen, kaotičen)", english: "tidy ≠ untidy, chaotic" },
          { german: "breit (širok) ≠ eng (ozek)", english: "wide ≠ narrow" },
          { german: "viel (veliko) ≠ wenig (malo)", english: "much ≠ little" },
          { german: "voll (poln) ≠ leer (prazen)", english: "full ≠ empty" },
          { german: "ruhig (miren) ≠ unruhig, laut (nemiren, glasen)", english: "calm ≠ restless, loud" },
          { german: "süß (sladek, srčkan) ≠ sauer (kisel, jezen)", english: "sweet, cute ≠ sour, angry" },
          { german: "lustig, witzig (smešen, zabaven) ≠ ernst (resen)", english: "funny, amusing ≠ serious" },
          { german: "komisch (čuden) ≠ normal (normalen)", english: "strange ≠ normal" },
          { german: "dick (debel) ≠ dünn (suh, tanek)", english: "fat ≠ thin" },
          { german: "traurig (žalosten) ≠ froh, fröhlich (vesel)", english: "sad ≠ happy, cheerful" },
          { german: "traurig (žalosten) ≠ glücklich (srečen)", english: "sad ≠ happy" },
          { german: "gut (dober) ≠ schlecht (slab)", english: "good ≠ bad" },
          { german: "gut (dober) ≠ böse (zloben)", english: "good ≠ evil" },
          { german: "stark (močan) ≠ schwach (šibek)", english: "strong ≠ weak" },
          { german: "faul (len) ≠ fleißig, tüchtig, brav (priden, delaven)", english: "lazy ≠ diligent, hardworking" },
          { german: "arm (reven) ≠ reich (bogat)", english: "poor ≠ rich" },
          { german: "bequem (udoben) ≠ unbequem (neudoben)", english: "comfortable ≠ uncomfortable" },
          { german: "angenehm (prijeten) ≠ unangenehm (neprijeten)", english: "pleasant ≠ unpleasant" },
          { german: "gemütlich (udoben, domačen, prijeten) ≠ ungemütlich (neudoben, neprijeten)", english: "cozy, homely, pleasant ≠ uncomfortable, unpleasant" },
          { german: "freundlich (prijazen) ≠ unfreundlich (neprijazen)", english: "friendly ≠ unfriendly" },
          { german: "locker (sproščen) ≠ streng (strog)", english: "relaxed ≠ strict" },
          { german: "frech (nespoštljiv, nesramen, predrzen) ≠ höflich (vljuden, spoštljiv)", english: "rude, cheeky ≠ polite, respectful" },
          { german: "klar (jasen) ≠ unklar (nejasen)", english: "clear ≠ unclear" },
          { german: "sauber (čist) ≠ schmutzig (umazan)", english: "clean ≠ dirty" }
        ]
      },
      {
        name: "E3: Beschreibe das Bild und kommentiere es",
        words: [
          { german: "Auf dem Bild (+Verb)", english: "In the picture" },
          { german: "links", english: "left" },
          { german: "rechts", english: "right" },
          { german: "vorne", english: "front" },
          { german: "hinten", english: "back" },
          { german: "oben", english: "above" },
          { german: "unten", english: "below" },
          { german: "rechts oben", english: "top right" },
          { german: "Auf dem Bild links", english: "in the picture left" },
          { german: "Auf dem Bild rechts", english: "in the picture right" },
          { german: "in der Mitte", english: "in the middle" },
          { german: "liegen", english: "to lie" },
          { german: "stehen", english: "to stand" },
          { german: "sein", english: "to be" },
          { german: "Links ist ...", english: "On the left is ..." },
          { german: "Rechts sind ...", english: "On the right are ..." },
          { german: "Oben sieht man (+Akkusativ)", english: "Above we see (man)" },
          { german: "Unten sehen wir (+Akkusativ)", english: "Below we see (wir)" },
          { german: "Es gibt ... (+Akkusativ)", english: "\"there is/there are\", are" },
          { german: "vielleicht", english: "maybe" },
          { german: "Auf dem Bild sehen wir eine Küche.", english: "In the picture, we see a kitchen." },
          { german: "Links steht eine Lampe.", english: "On the left stands a lamp." },
          { german: "Rechts gibt es eine Tür.", english: "On the right, there is a door. (gibt es!)" },
          { german: "In der Mitte liegt ein Teppich.", english: "In the middle lies a carpet." },
          { german: "Hinten sieht man einen Raum. (KOGA/KAJ!)", english: "At the back, we see a room." },
          { german: "Vorne stehen ein Tisch und ein Stuhl.", english: "In the front stand a table and a chair." },
          { german: "In der Mitte stehen drei Regale.", english: "In the middle stand three shelves." },
          { german: "Auf dem Bild gibt es eine Wohnung/ein Haus.", english: "In the picture, there is an apartment/house. (gibt es!)" },
          { german: "finden (er findet; ihr findet!)", english: "1. to find / 2. to think, seem" },
          { german: "zu alt", english: "too old" },
          { german: "zu billig", english: "too cheap" },
          { german: "zu jung", english: "too young" },
          { german: "zu teuer", english: "too expensive" },
          { german: "zu bequem", english: "too comfortable" },
          { german: "Ich finde das Haus sehr schön.", english: "I think the house is very beautiful." },
          { german: "Ich finde die Wohnung zu modern.", english: "I think the apartment is too modern." },
          { german: "Ich finde das Fenster zu groß.", english: "I think the window is too big." },
          { german: "Links steht ein Stuhl. Der Stuhl ist sehr komisch. Er ist zu klein.", english: "On the left stands a chair. The chair is very strange. It is too small." },
          { german: "Vorne gibt es eine Couch. Die Couch ist sehr schön. Sie ist modern.", english: "In the front, there is a couch. The couch is very beautiful. It is modern." },
          { german: "Hinten liegen Bücher. Die Bücher sind alt.", english: "At the back lie books. The books are old." }
        ]
      },
      {
        name: "E3: Kommunikation im Klassenzimmer",
        words: [
          { german: "Wer fehlt?", english: "Who is absent?" },
          { german: "niemand", english: "nobody" },
          { german: "Alle sind hier.", english: "Everyone is here." },
          { german: "Darf ich aufs Klo?", english: "May I go to the toilet?" },
          { german: "Nein.", english: "no" },
          { german: "Ja.", english: "yes" },
          { german: "später", english: "later" },
          { german: "Entschuldigung!", english: "Sorry!, I apologize!" },
          { german: "Entschuldigung für die Verspätung.", english: "Sorry for being late." },
          { german: "Ich habe mein Arbeitsblatt vergessen.", english: "I forgot my worksheet." },
          { german: "Ich habe meine Hausaufgabe vergessen.", english: "I forgot my homework." },
          { german: "Ich habe keine Ahnung.", english: "I have no idea." },
          { german: "Das ist kein Problem.", english: "That’s not a problem." },
          { german: "Darf ich weiter?", english: "May I continue?" },
          { german: "Noch nicht.", english: "Not yet." },
          { german: "Bitte schön.", english: "Here you go." },
          { german: "Danke.", english: "Thank you." },
          { german: "vielen Dank.", english: "Many thanks.1" },
          { german: "Dankeschön", english: "Many thanks.2" },
          { german: "bitte", english: "please" },
          { german: "Gern geschehen.", english: "you’re welcome" },
          { german: "Nichts zu danken.", english: "no problem" },
          { german: "Einen schönen Tag/Nachmittag noch.", english: "Have a nice day/afternoon." },
          { german: "Danke, ebenfalls!", english: "Thank you, likewise!1" },
          { german: "Danke, gleichfalls!", english: "Thank you, likewise!2" },
          { german: "Natürlich!", english: "of course1" },
          { german: "Selbstverständlich!", english: "of course2; obviously" },
          { german: "Freilich!", english: "of course3" },
          { german: "Bitte langsam.", english: "Please slowly." },
          { german: "Noch einmal, bitte.", english: "Once again, please." },
          { german: "Ich verstehe nicht.", english: "I don’t understand." },
          { german: "verstehen", english: "to understand" },
          { german: "Entschuldigung, ich habe eine Frage.", english: "Sorry, I have a question." },
          { german: "Wie bitte?", english: "Pardon?" },
          { german: "Können Sie das bitte wiederholen?", english: "Can you please repeat that?" },
          { german: "Was bedeutet ... auf Slowenisch?", english: "What does ... mean in Slovenian?" },
          { german: "Wie sagt man ... auf Deutsch?", english: "How do you say ... in German?" },
          { german: "Gesundheit!", english: "Bless you!" },
          { german: "Viel Glück!", english: "Good luck!" },
          { german: "Viel Erfolg!", english: "Much success!" },
          { german: "Wie geht's?", english: "How’s it going? / How are you?" },
          { german: "Wie geht es dir?", english: "How are you? / How’s it going?" },
          { german: "Wie geht es euch?", english: "How are you (plural)?" },
          { german: "Wie geht es Ihnen?", english: "How are you? (formal)" },
          { german: "Sehr gut, danke.", english: "Very good, thank you." },
          { german: "prima = toll = super", english: "great, awesome, super" },
          { german: "ausgezeichnet", english: "excellent" },
          { german: "fantastisch", english: "fantastic" },
          { german: "gut", english: "good" },
          { german: "ganz gut", english: "pretty good" },
          { german: "soso = so lala", english: "so-so" },
          { german: "Es geht.", english: "It’s okay." },
          { german: "schlecht", english: "bad" },
          { german: "sehr schlecht", english: "very bad" },
          { german: "Ich bin verliebt.", english: "I am in love." },
          { german: "Ich bin glücklich.", english: "I am happy." },
          { german: "Ich bin müde.", english: "I am tired." },
          { german: "Ich bin traurig.", english: "I am sad." },
          { german: "Ich bin krank.", english: "I am sick." },
          { german: "Ich bin hungrig.", english: "I am hungry." },
          { german: "Ich habe Angst.", english: "I am scared." },
          { german: "Gibt's Fragen?", english: "Any questions?" }
        ]
      }
    ],
    'E4': [
      {
        name: "E4: Essen und Trinken (Teil 1)",
        words: [
          { german: "Hast du Hunger? / Haben Sie Hunger?", english: "Are you hungry? Are you hungry (formal)?" },
          { german: "Bist du hungrig? / Sind Sie hungrig?", english: "Are you hungry? Are you hungry (formal)?" },
          { german: "Ich habe Hunger. / Ich habe keinen Hunger.", english: "I am hungry. / I am not hungry." },
          { german: "Hast du Durst? / Haben Sie Durst?", english: "Are you thirsty? Are you thirsty (formal)?" },
          { german: "Bist du durstig? / Sind Sie durstig?", english: "Are you thirsty? Are you thirsty (formal)?" },
          { german: "Ich habe Durst. / Ich habe keinen Durst.", english: "I am thirsty. / I am not thirsty." },
          { german: "satt / voll sein", english: "to be full (not hungry anymore)" },
          { german: "s Lebensmittel (-)", english: "food, groceries" },
          { german: "s Milchprodukt (-e)", english: "dairy product" },
          { german: "s Getränk (-e)", english: "beverage" },
          { german: "s Gemüse", english: "vegetable" },
          { german: "s Obst", english: "fruit" },
          { german: "Obst ist gesund.", english: "Fruit is healthy." },
          { german: "Gemüse schmeckt nicht gut.", english: "Vegetables don’t taste good." },
          { german: "s Fleischprodukt (-e)", english: "meat product" },
          { german: "e Fleischware (-n)", english: "meat product" },
          { german: "e Backware (-n)", english: "baked goods" },
          { german: "das Brot (-e)", english: "bread" },
          { german: "s Vollkornbrot", english: "whole grain bread" },
          { german: "s Weißbrot", english: "white bread" },
          { german: "s Schwarzbrot", english: "black bread" },
          { german: "s Ei (Eier)", english: "egg" },
          { german: "s Salz", english: "salt" },
          { german: "s Öl (-e)", english: "oil" },
          { german: "s Brötchen (-) / e Semmel (-n) (Ö)", english: "roll" },
          { german: "s Mehl (-e)", english: "flour" },
          { german: "r Honig (-e)", english: "honey" },
          { german: "r Reis", english: "rice" },
          { german: "e Nudel (-n)", english: "noodle" },
          { german: "e Butter", english: "butter" },
          { german: "e Margarine", english: "margarine" },
          { german: "r Käse (-)", english: "cheese" },
          { german: "e Milch", english: "milk" },
          { german: "e Sahne", english: "cream" },
          { german: "r Joghurt (-s)", english: "yogurt" },
          { german: "r Zucker (-)", english: "sugar" },
          { german: "e Marmelade (-n)", english: "jam" },
          { german: "s Fleisch", english: "meat" },
          { german: "r Fisch (-e)", english: "fish" },
          { german: "e Wurst (Würste)", english: "sausage" },
          { german: "r Schinken (-)", english: "ham" },
          { german: "r Salami (-s)", english: "salami" },
          { german: "s Hähnchen (-)", english: "chicken" },
          { german: "s Rindfleisch", english: "beef" },
          { german: "s Schweinefleisch", english: "pork" },
          { german: "e Kartoffel (-n)", english: "potato" },
          { german: "e Tomate (-n)", english: "tomato" },
          { german: "e Gurke (-n)", english: "cucumber" },
          { german: "e Karotte (-n)", english: "carrot" },
          { german: "r Paprika (-)", english: "bell pepper" },
          { german: "r Salat (-e)", english: "lettuce; salad" },
          { german: "r Kohl", english: "cabbage" },
          { german: "e Zwiebel (-n)", english: "onion" },
          { german: "r Knoblauch", english: "garlic" },
          { german: "e Bohne (-n)", english: "bean" },
          { german: "e Erbse (-n)", english: "pea" },
          { german: "r Apfel (Äpfel)", english: "apple" },
          { german: "e Birne (-n)", english: "pear" },
          { german: "e Banane (-n)", english: "banana" },
          { german: "e Orange (-n)", english: "orange" },
          { german: "e Mandarine (-n)", english: "mandarin" },
          { german: "e Zitrone (-n)", english: "lemon" },
          { german: "e Traube (-n)", english: "grape" },
          { german: "e Erdbeere (-n)", english: "strawberry" },
          { german: "e Himbeere (-n)", english: "raspberry" },
          { german: "e Kirsche (-n)", english: "cherry" },
          { german: "e Pflaume (-n)", english: "plum" },
          { german: "e Pfirsich (-e)", english: "peach" },
          { german: "e Aprikose (-n)", english: "apricot" },
          { german: "e Ananas", english: "pineapple" },
          { german: "e Melone (-n)", english: "melon" },
          { german: "e Wassermelone (-n)", english: "watermelon" },
          { german: "s Wasser", english: "water" },
          { german: "s Mineralwasser", english: "mineral water" },
          { german: "s Leitungswasser", english: "tap water" },
          { german: "r Saft (Säfte)", english: "juice" },
          { german: "r Apfelsaft", english: "apple juice" },
          { german: "r Orangensaft", english: "orange juice" },
          { german: "e Cola", english: "cola" },
          { german: "e Limonade (-n)", english: "lemonade" },
          { german: "r Tee (-s)", english: "tea" },
          { german: "r Kaffee (-s)", english: "coffee" },
          { german: "r Kakao (-s)", english: "cocoa" },
          { german: "r Wein (-e)", english: "wine" },
          { german: "s Bier (-e)", english: "beer" },
          { german: "essen", english: "to eat" },
          { german: "trinken", english: "to drink" },
          { german: "kochen", english: "to cook" },
          { german: "backen", english: "to bake" },
          { german: "schmecken", english: "to taste" },
          { german: "Das schmeckt gut.", english: "That tastes good." },
          { german: "Das schmeckt nicht.", english: "That doesn’t taste good." },
          { german: "lecker", english: "delicious" },
          { german: "frisch", english: "fresh" },
          { german: "gesund", english: "healthy" },
          { german: "ungesund", english: "unhealthy" },
          { german: "süß", english: "sweet" },
          { german: "salzig", english: "salty" },
          { german: "sauer", english: "sour" },
          { german: "bitter", english: "bitter" },
          { german: "scharf", english: "spicy" }
        ]
      },
      {
        name: "E4: Essen und Trinken (Teil 2)",
        words: [
          { german: "s Frühstück", english: "breakfast" },
          { german: "s Mittagessen", english: "lunch" },
          { german: "s Abendessen", english: "dinner" },
          { german: "e Jause (Ö)", english: "snack (Austria)" },
          { german: "s Pausenbrot", english: "snack" },
          { german: "e Mahlzeit (-en)", english: "meal" },
          { german: "r Hunger", english: "hunger" },
          { german: "r Durst", english: "thirst" },
          { german: "r Appetit", english: "appetite" },
          { german: "Guten Appetit!", english: "Enjoy your meal!" },
          { german: "e Speise (-n)", english: "dish, food" },
          { german: "e Suppe (-n)", english: "soup" },
          { german: "e Hauptspeise (-n)", english: "main course" },
          { german: "e Nachspeise (-n)", english: "dessert" },
          { german: "r Nachtisch (-e)", english: "dessert" },
          { german: "e Vorspeise (-n)", english: "appetizer" },
          { german: "e Beilage (-n)", english: "side dish" },
          { german: "s Menü (-s)", english: "menu" },
          { german: "e Speisekarte (-n)", english: "menu" },
          { german: "s Restaurant (-s)", english: "restaurant" },
          { german: "e Gaststätte (-n)", english: "tavern, restaurant" },
          { german: "s Lokal (-e)", english: "pub, local restaurant" },
          { german: "r Kellner (-)", english: "waiter" },
          { german: "e Kellnerin (-nen)", english: "waitress" },
          { german: "r Koch (Köche)", english: "cook (male)" },
          { german: "e Köchin (-nen)", english: "cook (female)" },
          { german: "bestellen", english: "to order" },
          { german: "servieren", english: "to serve" },
          { german: "zahlen", english: "to pay" },
          { german: "r Tisch (-e)", english: "table" },
          { german: "e Rechnung (-en)", english: "bill" },
          { german: "s Trinkgeld (-er)", english: "tip" },
          { german: "r Imbiss (-e)", english: "snack bar" },
          { german: "e Pommes frites", english: "French fries" },
          { german: "e Pizza (-s)", english: "pizza" },
          { german: "e Pasta", english: "pasta" },
          { german: "r Salat (-e)", english: "salad" },
          { german: "s Sandwich (-es)", english: "sandwich" },
          { german: "s Eis (-e)", english: "ice cream" },
          { german: "e Torte (-n)", english: "cake" },
          { german: "r Kuchen (-)", english: "cake" },
          { german: "s Gebäck", english: "pastries" },
          { german: "s Dessert (-s)", english: "dessert" },
          { german: "e Schokolade (-n)", english: "chocolate" },
          { german: "s Bonbon (-s)", english: "candy" },
          { german: "r Keks (-e)", english: "cookie" },
          { german: "r Kaffee (-s)", english: "coffee" },
          { german: "r Tee (-s)", english: "tea" },
          { german: "s Frühstücksflocken", english: "breakfast cereal" },
          { german: "s Müsli (-s)", english: "muesli" },
          { german: "e Küche (-n)", english: "kitchen; cuisine" },
          { german: "e Hausmannskost", english: "home cooking" },
          { german: "e Spezialität (-en)", english: "specialty" },
          { german: "vegetarisch", english: "vegetarian" },
          { german: "vegan", english: "vegan" },
          { german: "glutenfrei", english: "gluten-free" },
          { german: "laktosefrei", english: "lactose-free" },
          { german: "Was möchtest du essen?", english: "What would you like to eat?" },
          { german: "Was möchten Sie trinken?", english: "What would you like to drink? (formal)" },
          { german: "Ich möchte ...", english: "I would like ..." },
          { german: "Kann ich bitte ... haben?", english: "Can I please have ...?" },
          { german: "Was empfiehlt der Koch?", english: "What does the chef recommend?" },
          { german: "Was ist die Spezialität des Hauses?", english: "What is the house specialty?" },
          { german: "Die Rechnung, bitte.", english: "The bill, please." },
          { german: "Zusammen oder getrennt?", english: "Together or separate?" },
          { german: "Kann ich mit Karte zahlen?", english: "Can I pay by card?" },
          { german: "lecker", english: "delicious" },
          { german: "frisch", english: "fresh" },
          { german: "gesund", english: "healthy" },
          { german: "ungesund", english: "unhealthy" }
        ]
      },
      {
        name: "E4: Im Supermarkt",
        words: [
          { german: "r Supermarkt (-e)", english: "supermarket" },
          { german: "r Laden (Läden)", english: "shop" },
          { german: "e Bäckerei (-en)", english: "bakery" },
          { german: "e Metzgerei (-en)", english: "butcher shop" },
          { german: "r Markt (Märkte)", english: "market" },
          { german: "r Bauernmarkt (-märkte)", english: "farmers’ market" },
          { german: "e Kasse (-n)", english: "cash register" },
          { german: "r Kassierer (-)", english: "cashier (male)" },
          { german: "e Kassiererin (-nen)", english: "cashier (female)" },
          { german: "r Einkaufswagen (-)", english: "shopping cart" },
          { german: "r Einkaufskorb (-körbe)", english: "shopping basket" },
          { german: "e Tüte (-n)", english: "bag" },
          { german: "e Plastiktüte (-n)", english: "plastic bag" },
          { german: "e Stofftasche (-n)", english: "cloth bag" },
          { german: "e Einkaufsliste (-n)", english: "shopping list" },
          { german: "e Ware (-n)", english: "goods" },
          { german: "s Produkt (-e)", english: "product" },
          { german: "r Preis (-e)", english: "price" },
          { german: "e Rechnung (-en)", english: "receipt" },
          { german: "r Euro (-s)", english: "euro" },
          { german: "r Cent (-)", english: "cent" },
          { german: "kaufen", english: "to buy" },
          { german: "einkaufen", english: "to shop" },
          { german: "verkaufen", english: "to sell" },
          { german: "zahlen", english: "to pay" },
          { german: "kosten", english: "to cost" },
          { german: "Wie viel kostet das?", english: "How much does it cost?" },
          { german: "Das kostet ... Euro.", english: "That costs ... euros." },
          { german: "Haben Sie ...?", english: "Do you have ...? (formal)" },
          { german: "Wo finde ich ...?", english: "Where can I find ...?" },
          { german: "In welchem Gang ist ...?", english: "In which aisle is ...?" },
          { german: "bio", english: "organic" },
          { german: "frisch", english: "fresh" },
          { german: "regional", english: "regional" },
          { german: "importiert", english: "imported" },
          { german: "im Angebot", english: "on offer" },
          { german: "reduziert", english: "reduced" },
          { german: "das Sonderangebot (-e)", english: "special offer" },
          { german: "das Pfand (-er)", english: "deposit (for bottles)" },
          { german: "r Rabatt (-e)", english: "discount" },
          { german: "e Karte (-n)", english: "card (credit/debit)" },
          { german: "bar zahlen", english: "to pay in cash" },
          { german: "mit Karte zahlen", english: "to pay by card" },
          { german: "Kann ich mit Karte zahlen?", english: "Can I pay by card?" },
          { german: "Haben Sie eine Kundenkarte?", english: "Do you have a loyalty card?" },
          { german: "Kann ich eine Tüte haben?", english: "Can I have a bag?" },
          { german: "Ich brauche eine Einkaufsliste.", english: "I need a shopping list." },
          { german: "Das ist zu teuer.", english: "That’s too expensive." },
          { german: "Haben Sie etwas Billigeres?", english: "Do you have something cheaper?" }
        ]
      }
    ],
    'E5': [
      {
        name: "E5: Familie und Freunde",
        words: [
          { german: "e Familie (-n)", english: "family" },
          { german: "r Freund (-e)", english: "friend (male)" },
          { german: "e Freundin (-nen)", english: "friend (female); girlfriend" },
          { german: "r Vater (Väter)", english: "father" },
          { german: "e Mutter (Mütter)", english: "mother" },
          { german: "r Papa (-s)", english: "dad" },
          { german: "e Mama (-s)", english: "mom" },
          { german: "r Opa (-s)", english: "grandfather" },
          { german: "e Oma (-s)", english: "grandmother" },
          { german: "s Kind (-er)", english: "child" },
          { german: "r Sohn (Söhne)", english: "son" },
          { german: "e Tochter (Töchter)", english: "daughter" },
          { german: "r Bruder (Brüder)", english: "brother" },
          { german: "e Schwester (-n)", english: "sister" },
          { german: "e Geschwister", english: "siblings" },
          { german: "r Onkel (-)", english: "uncle" },
          { german: "e Tante (-n)", english: "aunt" },
          { german: "r Cousin (-s)", english: "cousin (male)" },
          { german: "e Cousine (-n)", english: "cousin (female)" },
          { german: "r Neffe (-n)", english: "nephew" },
          { german: "e Nichte (-n)", english: "niece" },
          { german: "e Großeltern", english: "grandparents" },
          { german: "r Großvater (Großväter)", english: "grandfather" },
          { german: "e Großmutter (Großmütter)", english: "grandmother" },
          { german: "e Eltern", english: "parents" },
          { german: "r Mann (Männer)", english: "husband; man" },
          { german: "e Frau (-en)", english: "wife; woman" },
          { german: "r Ehemann (Ehemänner)", english: "husband" },
          { german: "e Ehefrau (-en)", english: "wife" },
          { german: "r Partner (-)", english: "partner (male)" },
          { german: "e Partnerin (-nen)", english: "partner (female)" },
          { german: "r Lebenspartner (-)", english: "life partner (male)" },
          { german: "e Lebenspartnerin (-nen)", english: "life partner (female)" },
          { german: "verheiratet sein", english: "to be married" },
          { german: "geschieden sein", english: "to be divorced" },
          { german: "ledig sein", english: "to be single" },
          { german: "verwitwet sein", english: "to be widowed" },
          { german: "zusammenleben", english: "to live together" },
          { german: "s Baby (-s)", english: "baby" },
          { german: "r Enkel (-)", english: "grandson" },
          { german: "e Enkelin (-nen)", english: "granddaughter" },
          { german: "s Haustier (-e)", english: "pet" },
          { german: "r Hund (-e)", english: "dog" },
          { german: "e Katze (-n)", english: "cat" },
          { german: "r Vogel (Vögel)", english: "bird" },
          { german: "r Fisch (-e)", english: "fish" },
          { german: "r Hamster (-)", english: "hamster" },
          { german: "e Maus (Mäuse)", english: "mouse" },
          { german: "s Meerschweinchen (-)", english: "guinea pig" },
          { german: "r Kanarienvogel (-)", english: "canary" },
          { german: "s Pferd (-e)", english: "horse" },
          { german: "e Familie (-n)", english: "family" },
          { german: "Wie groß ist deine Familie?", english: "How big is your family?" },
          { german: "Hast du Geschwister?", english: "Do you have siblings?" },
          { german: "Ich habe einen Bruder.", english: "I have a brother." },
          { german: "Ich habe zwei Schwestern.", english: "I have two sisters." },
          { german: "Ich bin Einzelkind.", english: "I am an only child." },
          { german: "Wo wohnen deine Eltern?", english: "Where do your parents live?" },
          { german: "Hast du ein Haustier?", english: "Do you have a pet?" },
          { german: "Wie heißt dein Hund?", english: "What’s your dog’s name?" }
        ]
      },
      {
        name: "E5: Freizeitaktivitäten",
        words: [
          { german: "e Freizeit", english: "free time" },
          { german: "s Hobby (-s)", english: "hobby" },
          { german: "Was machst du in deiner Freizeit?", english: "What do you do in your free time?" },
          { german: "Ich gehe ...", english: "I go ..." },
          { german: "spazieren gehen", english: "to go for a walk" },
          { german: "wandern", english: "to hike" },
          { german: "joggen", english: "to jog" },
          { german: "laufen", english: "to run" },
          { german: "Fahrrad fahren", english: "to cycle" },
          { german: "schwimmen", english: "to swim" },
          { german: "tauchen", english: "to dive" },
          { german: "Ski fahren", english: "to ski" },
          { german: "Snowboard fahren", english: "to snowboard" },
          { german: "reiten", english: "to ride (horse)" },
          { german: "klettern", english: "to climb" },
          { german: "zelten", english: "to camp" },
          { german: "reisen", english: "to travel" },
          { german: "kochen", english: "to cook" },
          { german: "backen", english: "to bake" },
          { german: "lesen", english: "to read" },
          { german: "Bücher lesen", english: "to read books" },
          { german: "Musik hören", english: "to listen to music" },
          { german: "singen", english: "to sing" },
          { german: "tanzen", english: "to dance" },
          { german: "malen", english: "to paint" },
          { german: "zeichnen", english: "to draw" },
          { german: "fotografieren", english: "to photograph" },
          { german: "Fotos machen", english: "to take photos" },
          { german: "basteln", english: "to craft" },
          { german: "sammeln", english: "to collect" },
          { german: "Computerspiele spielen", english: "to play video games" },
          { german: "zocken", english: "to game" },
          { german: "Schach spielen", english: "to play chess" },
          { german: "Karten spielen", english: "to play cards" },
          { german: "Brettspiele spielen", english: "to play board games" },
          { german: "Fußball spielen", english: "to play soccer" },
          { german: "Basketball spielen", english: "to play basketball" },
          { german: "Volleyball spielen", english: "to play volleyball" },
          { german: "Tennis spielen", english: "to play tennis" },
          { german: "Tischtennis spielen", english: "to play table tennis" },
          { german: "ins Kino gehen", english: "to go to the cinema" },
          { german: "ins Theater gehen", english: "to go to the theater" },
          { german: "ins Konzert gehen", english: "to go to a concert" },
          { german: "ins Museum gehen", english: "to go to a museum" },
          { german: "in die Disko gehen", english: "to go to a disco" },
          { german: "Freunde treffen", english: "to meet friends" },
          { german: "fernsehen", english: "to watch TV" },
          { german: "Serien gucken", english: "to watch series" },
          { german: "Filme schauen", english: "to watch movies" },
          { german: "im Internet surfen", english: "to surf the internet" },
          { german: "chatten", english: "to chat (online)" },
          { german: "shoppen", english: "to shop" },
          { german: "ausruhen", english: "to rest" },
          { german: "schlafen", english: "to sleep" },
          { german: "Was machst du gern in deiner Freizeit?", english: "What do you like to do in your free time?" },
          { german: "Ich mache gern ...", english: "I like to do ..." },
          { german: "Ich spiele gern ...", english: "I like to play ..." },
          { german: "Ich gehe gern ...", english: "I like to go ..." },
          { german: "Hast du ein Lieblingshobby?", english: "Do you have a favorite hobby?" },
          { german: "Mein Lieblingshobby ist ...", english: "My favorite hobby is ..." }
        ]
      },
      {
        name: "E5: Tagesablauf",
        words: [
          { german: "r Tagesablauf (-äufe)", english: "daily routine" },
          { german: "aufstehen", english: "to get up" },
          { german: "Ich stehe um 7 Uhr auf.", english: "I get up at 7 o’clock." },
          { german: "schlafen gehen", english: "to go to bed" },
          { german: "Ich gehe um 22 Uhr schlafen.", english: "I go to bed at 10 p.m." },
          { german: "frühstücken", english: "to have breakfast" },
          { german: "zu Mittag essen", english: "to have lunch" },
          { german: "zu Abend essen", english: "to have dinner" },
          { german: "duschen", english: "to shower" },
          { german: "badende", english: "to bathe" },
          { german: "sich waschen", english: "to wash oneself" },
          { german: "sich die Zähne putzen", english: "to brush one’s teeth" },
          { german: "sich anziehen", english: "to get dressed" },
          { german: "sich ausziehen", english: "to undress" },
          { german: "sich umziehen", english: "to change clothes" },
          { german: "sich schminken", english: "to put on makeup" },
          { german: "sich kämmen", english: "to comb one’s hair" },
          { german: "sich die Haare föhnen", english: "to blow-dry one’s hair" },
          { german: "zur Schule gehen", english: "to go to school" },
          { german: "zur Arbeit gehen", english: "to go to work" },
          { german: "nach Hause kommen", english: "to come home" },
          { german: "Hausaufgaben machen", english: "to do homework" },
          { german: "lernen", english: "to study, learn" },
          { german: "arbeiten", english: "to work" },
          { german: "einkaufen gehen", english: "to go shopping" },
          { german: "kochen", english: "to cook" },
          { german: "essen", english: "to eat" },
          { german: "trinken", english: "to drink" },
          { german: "fernsehen", english: "to watch TV" },
          { german: "schlafen", english: "to sleep" },
          { german: "aufwachen", english: "to wake up" },
          { german: "morgen", english: "morning" },
          { german: "vormittags", english: "in the morning" },
          { german: "mittags", english: "at noon" },
          { german: "nachmittags", english: "in the afternoon" },
          { german: "abends", english: "in the evening" },
          { german: "nachts", english: "at night" },
          { german: "Wie ist dein Tagesablauf?", english: "What’s your daily routine?" },
          { german: "Was machst du morgens?", english: "What do you do in the morning?" },
          { german: "Um wie viel Uhr stehst du auf?", english: "What time do you get up?" },
          { german: "Wann gehst du schlafen?", english: "When do you go to bed?" },
          { german: "Ich habe einen stressigen Tag.", english: "I have a stressful day." },
          { german: "Ich habe einen ruhigen Tag.", english: "I have a calm day." }
        ]
      }
    ]
  }
};